name: Build LaTeX document

on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: notas-de-aula.tex
      - name: Commit report
        run: |
          git config --global user.email "line.asramos@gmail.com"
          git config --global user.name "Aline Pereira"
          git commit -am "Add pdf to repo"
          git push
