name: Build LaTeX document

on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: notas-de-aula.tex
      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: PDF
      #     path: notas-de-aula.pdf
      - name: Commit created PDF
        run: |
          git config user.email "line.asramos@gmail.com"
          git config user.name "Aline Pereira"
          git add .
          git commit
          git push
